### ISSUE TITLE
PresenceModules broken

### ISSUE THREAD

**Issue by Kordump** [pipoteam/pipobot#20]
PresenceModules seems to be broken, the `answer` method is never called.

**Comment by sleduc** [comment]
If you really mean `answer` it is normal : the method is supposed to be `do_answer`, as stated in the documentation : https://github.com/pipoteam/pipobot/blob/master/doc/source/modules.rst#presencemodule-1

You can also see the `RecordUsers` plugin for example of implementation : https://github.com/pipoteam/pipobot/blob/master/pipobot/lib/modules.py#L446

PS: I am not sure why the method is do_answer here, which is not very consistent with other types of modules, but at least it should work...
