### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by sleduc** [pipoteam/pipobot#9]
Pipobot is now using sleekxmpp as "XMPP library", which has a python3 version !

Other dependencies of the "core" of pipobot (without looking at pipobot-modules) are yaml, sleekxmpp, sqlalchemy and they all have a python3 version !

The "conversion" to python3 should not be a problem for "the core", some dependencies of pipobot-modules could be a problem though…

Also writing a python3 version means maintaining it and testing it with new changes along with the python2 version.

**Comment by nim65s** [comment]
Python3 is in Debian Stable now… Maybe we can start to wonder if we still want a python2 version ?

**Comment by xouillet** [comment]
Why not, but we have to check that none of the pipobot-modules uses a python2-only library…

**Comment by nim65s** [comment]
Good news, I'm currently kind of doing this :)

**Comment by sleduc** [comment]
The porting was in progress in the branches python3 of pipobot/pipobot-modules, but there is still work to do.
My first idea was : 
  * to add the python3 support in a branch (python3)
  * to make the python3 branch work with both python3 and python2 (I started to add unit test to check this).
  * the python3 branch becomes master

The first step should be OK for pipobot, maybe not for pipobot-modules.
The second is still in progress.
Tthe third must wait the 2 others to be done :)

**Comment by Linkid** [comment]
Hi!
How can I help to migrate to python 3 ?
Thanks :)

**Comment by sleduc** [comment]
Hi !

There are "python3" branches on both "pipobot" and "pipobot-modules" that should be quite functional (at least I have been using them for a while).
The main thing that is missing is a sync between "python3" and "master" branches, so basically to port the latest commits on master to the python3 branch.
It should not be too complicated on "pipobot", but probably harder on "pipobot-modules" because more things were added on master after the porting to python3 began.

NOTE: initially (well in 2015), the idea was to have a python3 branch working with both python2 and python3.
At this point, and since python2 is now deprecated, IMO the support for python2 could be simply dropped making the porting/testing easier.

**Comment by xouillet** [comment]
Yup, done ! #25
